version: "3"
services:
  app:
    build: .
    volumes:
      - ./code:/code
    ports:
      - "3000:3000"

  database:
    image: postgres:latest
    environment:
      - POSTGRES_PASSWORD=dbpass
    volumes:
      - db:/var/lib/postgres/data

volumes:
  db:
